version:  '3.7'
services:
  mysql:
    image: mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080

  nginx:
    image: nginx:1.17.10-alpine
    restart: on-failure
    volumes:
      - './src/my-symfony-app/public/:/usr/src/app'
      - './etc/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: etc/docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    user: 1000:1000