version:  '3.7'
services:
  mysql:
    image: mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '${ADMINER_PORT}:8080'

  nginx:
    image: nginx:1.17.10-alpine
    restart: on-failure
    volumes:
      - './:/usr/src/app'
      - './etc/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: etc/docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    volumes:
      - './:/usr/src/app'
    user: ${LOCAL_USER}